export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';

export const INIT_PRODUCTS = 'INIT_PRODUCTS';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILED = 'FETCH_PRODUCTS_FAILED';

export const ADDED_PRODUCT_TO_BASKET = 'ADDED_PRODUCT_TO_BASKET';
export const REMOVED_PRODUCT_FROM_BASKET = 'REMOVED_PRODUCT_FROM_BASKET';