export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const SET_CATEGORY = 'SET_CATEGORY';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAILED = 'FETCH_CATEGORIES_FAILED';